export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const FETCH_CLIENT_BY_ID_REQUEST = 'FETCH_CLIENT_BY_ID_REQUEST';
export const FETCH_CLIENT_BY_ID_SUCCESS = 'FETCH_CLIENT_BY_ID_SUCCESS';
export const FETCH_CLIENT_BY_ID_FAILURE = 'FETCH_CLIENT_BY_ID_FAILURE';

export const CREATE_CLIENT = 'CREATE_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';

export const UPDATE_CLIENT_FIELD = 'UPDATE_CLIENT_FIELD';