export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';

export const FETCH_ROLE_BY_ID_REQUEST = 'FETCH_ROLE_BY_ID_REQUEST';
export const FETCH_ROLE_BY_ID_SUCCESS = 'FETCH_ROLE_BY_ID_SUCCESS';
export const FETCH_ROLE_BY_ID_FAILURE = 'FETCH_ROLE_BY_ID_FAILURE';

export const CREATE_ROLE = 'CREATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';

export const UPDATE_ROLE_FIELD = 'UPDATE_ROLE_FIELD';
